config/routes.rb
Rails.application.routes.draw do
  resources :reviews, except: [ :index ]
  root 'welcome#index'
  get 'login'     => 'sessions#new'
  post 'login'    => 'sessions#create'
  delete 'logout'    => 'sessions#destroy'

  resources :places
  get 'category/:cat' => 'places#index_by_cat', as: :category
  get 'perk/:perk' => 'places#index_by_perk', as: :perk
  resources :users, path_names: { new: 'signup' }
  get 'static_pages/apps'

  get 'static_pages/about'

end

app/models/user.rb
class User < ActiveRecord::Base
  extend FriendlyId
  friendly_id :processed_name_candidates, use: :slugged

  acts_as_tagger
  ActsAsTaggableOn.delimiter = [',','，']

  def processed_name
      Pinyin.t(name)
  end

  def processed_name_candidates
    [
      :processed_name,
      [:processed_name, (User.where(name: name).count - 1).to_s]
    ]
  end

  attr_accessor :remember_token
  has_secure_password
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 30 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
    format: { with: VALID_EMAIL_REGEX },
    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  has_many :introduced_places, class_name: "Place", foreign_key: "introducer_id", inverse_of: :introducer
  has_many :reviews
  has_many :reviewed_places, class_name: "Place", foreign_key: "reviewers_id", through: :reviews, source: :place

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
      BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user, only: [:index, :destroy]
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.paginate(page: params[:page])
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        log_in @user
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :wechat, :phone, :email, :password, :password_confirmation)
    end

    # Confirms a logged-in user
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

    # Confirms the correct user
    def correct_user
      @user = User.friendly.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="row">
<div class="col-md-6 col-md-offset-3">
  <%= form_for(@user) do |f| %>
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="field">
      <%= f.label :wechat %><br>
      <%= f.text_field :wechat, class: "form-control" %>
    </div>
    <div class="field">
      <%= f.label :phone %><br>
      <%= f.text_field :phone, class: "form-control"  %>
    </div>
    <div class="field">
      <%= f.label :email %><br>
      <%= f.email_field :email, class: "form-control"  %>
    </div>
    <div class="field">
      <%= f.label :password %><br>
      <%= f.password_field :password, class: "form-control"  %>
    </div>
    <div class="field">
      <%= f.label :password_confirmation %><br>
      <%= f.password_field :password_confirmation, class: "form-control"  %>
    </div>
    <div class="actions">
      <%= f.submit "保存", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<%= will_paginate %>
<ul class="users">
    <% @users.each do |user| %>
      <li>
        <%= link_to user.name, user %>
        <span class="label label-danger"><%= link_to 'delete', user, method: :delete, data: { confirm: 'Are you sure?' } %></span>
      </li>
    <% end %>
</ul>
<%= will_paginate %>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Wechat:</strong>
  <%= @user.wechat %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @user.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<h2>添加的商户</h2>
<ul>
  <% @user.introduced_places.each do |place| %>
    <li><div><%= link_to place.name, place_url(Place.friendly.find(place.id)) %></div>
      <div><%= place.location %></div></li>
  <% end %>
</ul>

<h3>使用的 tag</h3>
<ul>
  <% @user.owned_tags.sort_by {|t| t.taggings_count}.reverse.each do |t| %>
    <li><%= link_to t.name, perk_path(perk: t.name) %></li>
  <% end %>
</ul>

<h2><%= @user.name %>的点评</h2>
<% @user.reviews.order(id: :desc).take(3).each do |rev| %>
  <div>对 <%= link_to Place.find(rev.place_id).name, place_url(Place.find(rev.place_id)) %> 的评论：
  <div><h4><%= link_to rev.title, review_url(Review.find(rev.id)) %></h4></div>
  <div>评分 <%= rev.rating %></div>
  <div><%= rev.contents %></div>
  <hr>
<% end %>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>