config/routes.rb
Rails.application.routes.draw do
  resources :reviews, except: [ :index ]
  root 'welcome#index'
  get 'login'     => 'sessions#new'
  post 'login'    => 'sessions#create'
  delete 'logout'    => 'sessions#destroy'

  resources :places
  get 'category/:cat' => 'places#index_by_cat', as: :category
  get 'perk/:perk' => 'places#index_by_perk', as: :perk
  resources :users, path_names: { new: 'signup' }
  get 'static_pages/apps'

  get 'static_pages/about'

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :logged_in_user, only: [:create, :edit, :update, :destroy]
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @place = Place.find(params[:review][:place_id].to_i)
    @review = current_user.reviews.build(review_params)
    @review.place_id = @place.id

    respond_to do |format|
      if @review.save
        format.html { redirect_to place_path(Place.friendly.find(@place.id)), notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Confirms a logged-in user
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:title, :contents, :rating)
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= form_for (@review) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>* 代表必填</p>
  <p>** 代表可不填写，但如填写必须超过20字</p>
  <div class="field">
    <%= f.label "标题" %><br>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label "评分 *" %><br>
    <%= f.select :rating, (1..5).to_a %>
  </div>

  <%= f.hidden_field :place_id, :value => @place.nil? ? @review.place_id : @place.id %>

  <div class="field">
    <%= f.label "点评内容 **" %><br>
    <%= f.text_area :contents, size: "40x10" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form' %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Reviews</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form' %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p><%= link_to User.find(@review.user_id).name, user_path(User.find(@review.user_id)) %> 对
   <%= link_to Place.find(@review.place_id).name, place_path(Place.find(@review.place_id)) %> 的评价
<h1><%= @review.title %></h1>

<h3>评分：<%= @review.rating %></h3>
<div><%= @review.contents %></div>

<% if (!current_user.nil? && (current_user.id == @review.user_id)) %>
  <%= link_to 'Edit', edit_review_path(@review) %> |
<% end %>
<%= link_to 'Back', place_path(Place.friendly.find(@review.place_id)) %>