config/routes.rb
Rails.application.routes.draw do
  resources :reviews, except: [ :index ]
  root 'welcome#index'
  get 'login'     => 'sessions#new'
  post 'login'    => 'sessions#create'
  delete 'logout'    => 'sessions#destroy'

  resources :places
  get 'category/:cat' => 'places#index_by_cat', as: :category
  get 'perk/:perk' => 'places#index_by_perk', as: :perk
  resources :users, path_names: { new: 'signup' }
  get 'static_pages/apps'

  get 'static_pages/about'

end

app/models/place.rb
class Place < ActiveRecord::Base
  extend FriendlyId
  friendly_id :processed_name_candidates, use: :slugged

  acts_as_taggable
  acts_as_taggable_on :cat, :perk, :exp
  ActsAsTaggableOn.delimiter = [',','，']

  def processed(str)
    Pinyin.t(str)
  end

  def processed_city
    processed(city)
  end

  def processed_province
    processed(province)
  end

  def processed_name
    processed(name)
  end

  def processed_community
    community.nil? ? "" : processed(community)
  end

  def processed_name_candidates
    [
      "#{processed_province}-#{processed_city}-#{processed_name}",
      [:processed_province, :processed_city, :processed_community, :processed_name],
      [:processed_province, :processed_city, :processed_community, :processed_name, (Place.where(name: name).count - 1).to_s]
    ]
  end

  validates :name, presence: true, length: { maximum: 30 }
  validates :province, presence: true
  validates :city, presence: true
  validates :cat_list, presence: true

  belongs_to :introducer, class_name: "User", foreign_key: "introduced_places_id", inverse_of: :introduced_places
  has_many :reviews, dependent: :destroy
  has_many :reviewers, class_name: "User", foreign_key: "reviewed_places_id", through: :reviews, source: :user

  def place_cats
    [
      ['餐饮',
       ['正餐', '点心', '早午餐', '下午茶', '零食', '饮料']],
      ['游乐',
       ['游乐场', '公园', '运动场馆', '展览', '郊野']],
      ['服务',
       ['理发', '摄影', '托管', '卫生医疗']],
      ['购物',
       ['食品', '用品', '玩具', '书籍']]
    ]
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :logged_in_user, only: [:create, :update]
  before_action :set_place, only: [:show, :edit, :update, :destroy]

  helper PlacesHelper

  # GET /places
  # GET /places.json
  def index
    @places = Place.all
  end

  # GET /places/1
  # GET /places/1.json
  def show
  end

  def index_by_cat
    @places_by_cat = Place.tagged_with(params[:cat]).uniq
  end

  def index_by_perk
    @places_by_perk = Place.tagged_with(params[:perk]).uniq
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  # POST /places.json
  def create
    @place = current_user.introduced_places.build(place_params)
    current_user.tag(@place, with: params[:place][:perk_list].split(/,|，/), on: :perk)

    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    current_user.tag(@place, with: params[:place][:perk_list].split(/,|，/) - (@place.all_perk_list & params[:place][:perk_list].split(/,|，/)), on: :perk)
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url, notice: 'Place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.friendly.find(params[:id])
    end

    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:name, :province, :city, :community, :nearby, :location, :phone, :opentime, :cat_list, :perk_list, :cat_list => [], :perk_list => [])
    end
end

app/helpers/places_helper.rb
module PlacesHelper
  include ActsAsTaggableOn::TagsHelper

  def perks_count_by_usage
    perks_count = Hash.new
    User.find_each do |u|
      u.owned_taggings.group_by { |t| t.tag_id }.each do |key, value|
        perks_count.has_key?(key) ?
          perks_count[key] += value.size :
          perks_count[key] = value.size
      end
    end
    return perks_count
  end

  # => e.g. { perk1: 13, perk2: 7, perk3:... }
end

app/views/places/_form.html.erb
<%= form_for(@place) do |f| %>
  <% if @place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@place.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
      <% @place.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label "类别" %><br>
    <% # max allowed options = 3. But select sends an empty hidden field %>
    <% # to avoid the mass edit gotcha, see api.rubyonrails.org/classes/ActionView/Helpers/FormOptionsHelper.html#method-i-select %>
    <%= f.select :cat_list, @place.place_cats, { prompt: "类别", selected: @place.cat_list }, { multiple: true, size: 4 } %>
  </div>
  <div class="field">
    <%= f.label :province %><br>
    <%= f.text_field :province %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :community %><br>
    <%= f.text_field :community %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :nearby %><br>
    <%= f.text_field :nearby %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :opentime %><br>
    <%= f.text_field :opentime %>
  </div>
  <div>
    请在下面框中输入您希望给商户添加的标签，标签可以描述商户拥有的设施，如：宝宝椅，宝宝餐具，或描述商户的人员配备，如：导乐，灯光师，或其他您认为有助于他人了解商户情况的词或短语。标签请用中文或英文逗号分隔。
  </div>
  <div class="field">
    <%= f.label "特色标签" %><br>
    <%= f.text_field :perk_list, value: @place.all_perk_list %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/places/edit.html.erb
<h1>Editing Place</h1>

<%= render 'form' %>

<%= link_to 'Show', @place %> |
<%= link_to 'Back', places_path %>

app/views/places/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Places</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th>Phone</th>
      <th>Open Time</th>
      <th colspan="3"></th>
      <th colspan="3"></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @places.each do |place| %>
      <tr>
        <td><%= place.name %></td>
        <td><%= place.location %></td>
        <td><%= place.phone %></td>
        <td><%= place.opentime %></td>
        <td><%= link_to 'Show', place %></td>
        <td><%= link_to 'Edit', edit_place_path(place) %></td>
        <td><%= link_to 'Destroy', place, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Place', new_place_path %>

app/views/places/index_by_cat.html.erb
<p id="notice"><%= notice %></p>

<h1>带有<%= params[:cat] %>标签的商家</h1>

<ul>
  <% @places_by_cat.each do |place| %>
    <li><%= link_to place.name, place_path(place.id) %></li>
  <% end %>

<br>

<%= link_to 'New Place', new_place_path %>

app/views/places/index_by_perk.html.erb
<p id="notice"><%= notice %></p>

<h1>带有<%= params[:perk] %>标签的商家</h1>

<ul>
  <% @places_by_perk.each do |place| %>
    <li><%= link_to place.name, place_path(Place.friendly.find(place.id)) %></li>
  <% end %>

<br>

<%= link_to 'New Place', new_place_path %>

app/views/places/new.html.erb
<h1>New Place</h1>

<%= render 'form' %>

<%= link_to 'Back', places_path %>

app/views/places/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>名称</strong>
  <%= @place.name %>
</p>

<p id="test-cat">
  <strong>类别</strong>
  <% @place.cat.each do |tag| %>
    <%= link_to tag.name, category_path(cat: tag.name) %>
  <% end %>
</p>

<p id="test-perk">
  <strong>特色</strong>
  <% @place.perk.uniq.sort_by { |perk| perks_count_by_usage[perk.id] }.reverse.take(10).each do |tag| %>
    <%= link_to tag.name, perk_path(tag.name) %>
  <% end %>
</p>

<p id="test-rating">
  <strong>评分</strong>
  <%= ((@place.reviews.reduce(0) { |total, rev| total += rev.rating }).to_f / @place.reviews.count).round(2) %>
</p>

<p>
  <strong>位置</strong>
  <%= @place.province %>
  <%= @place.city %>
  <%= @place.community %>
  <%= @place.location %>
</p>

<p>
  <strong>电话</strong>
  <%= @place.phone %>
</p>

<p>
  <strong>营业时间</strong>
  <%= @place.opentime %>
</p>

<% unless (@place.introducer_id.nil?) %>
  <p>本商户由 <%= link_to User.find(@place.introducer_id).name, user_path(User.find(@place.introducer_id)) %> 添加。</p>
<% end %>

<% unless @place.reviews.empty? %>
<h2>点评</h2>

<% @place.reviews.order(id: :desc).first(3).each do |rev| %>
  <div>
    <h3><%= link_to rev.title, review_path(Review.find(rev.id)) %></h3>
    <div>作者 <%= link_to User.find(rev.user_id).name, user_path(User.find(rev.user_id)) %> 评分 <%= rev.rating %></div>
    <div><%= rev.contents %></div>
  </div>
<% end %>
<% end %>

<% # TODO: 添加 more 按钮，点击后展开所有点评 %>

<% if !current_user.nil? %>
  <% if @place.reviews.empty? %>
    <h2>我要点评</h2>
  <% else %>
    <h2>我也要点评</h2>
  <% end %>
  <% @review = Review.new %>
  <%= render 'reviews/form' %>
  <%= link_to 'Edit', edit_place_path(Place.friendly.find(@place.id)) %> |
<% end %>
<%= link_to 'Back', places_path %>