config/routes.rb
Rails.application.routes.draw do
  resources :reviews, except: [ :index ]
  root 'welcome#index'
  get 'login'     => 'sessions#new'
  post 'login'    => 'sessions#create'
  delete 'logout'    => 'sessions#destroy'

  resources :places
  get 'category/:cat' => 'places#index_by_cat', as: :category
  get 'perk/:perk' => 'places#index_by_perk', as: :perk
  resources :users, path_names: { new: 'signup' }
  get 'static_pages/apps'

  get 'static_pages/about'

end

app/views/layouts/_footer.html.erb
<footer>
<nav class="nav navbar-default">
  <div class="navbar-text">© 2015. U.S.S. Enterprise.</div>
  <div class="navbar-right">
    <ul class="nav navbar-nav">
      <li><%= link_to "Blog", '#' %></li>
      <li><%= link_to "About us", '#' %></li>
    </ul>
</nav>
</footer>

app/views/layouts/_header.html.erb
<header>
<div>
  <nav class="navbar navbar-default">
    <%= link_to "Wawale App", root_path, class: "navbar-brand", id: "logo" %>
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "About", static_pages_about_path %></li>
      <li><%= link_to "Apps", static_pages_apps_path %></li>
      <% if logged_in? %>
        <% if current_user.admin? %>
          <li><%= link_to "Users", users_path %></li>
        <% end %>
        <li><%= link_to "Places", places_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Account <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Profile", user_path(current_user) %></li>
            <li><%= link_to "Settings", edit_user_path(current_user) %></li>
            <li class="divider"></li>
            <li>
              <%= link_to "Log out", logout_path, method: "delete" %>
            </li>
          </ul>
        </li>
      <% else %>
        <li><%= link_to "Log in", login_path %></li>
      <% end %>
    </ul>
  </nav>
</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WawaleApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>

  <%= yield %>
  <%= debug(params) if Rails.env.development? %>
  <%= render 'layouts/footer' %>
</body>
</html>